## Project
name: portfolio_tracking
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  portfolio_tracking:
    +materialized: view
    staging:    # Data storage layer
      +materialized: ephemeral
      +schema: STAGING
    refined:    # Refined data layer
      +materialized: view
      +schema: REFINED
    marts:      # Data delivery layer 
      +materialized: table
      +schema: MART_PORTFOLIO
snapshots:
  portfolio_tracking:
    +target_schema: SNAPSHOTS
seeds:
 +schema : "{{target.schema}}_SEED_DATA"
 portfolio_tracking:
  ABC_SECURIY_INFO:
    +post-hook:
    - "UPDATE {{ this }} SET LOAD_TS = '{{ run_started_at }}' WHERE LOAD_TS is null"
    +column_types:
      LOAD_TS : TIMESTAMP
