tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DEV_ANALYTICS
      schema: DEV
      warehouse: DEV_DBT_WH
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DEV_ANALYTICS
      schema: PROD
      warehouse: DEV_DBT_WH
      threads: 8
