tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DEV_ANALYTICS
      schema: dev
      warehouse: DEV_DBT_WH
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DEV_ANALYTICS
      schema: prod
      warehouse: DEV_DBT_WH
      threads: 8
