CREATE DATABASE DEV_ANALYTICS;

CREATE SCHEMA DBT;

CREATE SCHEMA COMMERCIAL;

CREATE ROLE DEV_DBT_ROLE;

CREATE USER DEV_DBT_USER;

GRANT ROLE DEV_DBT_ROLE TO USER DEV_DBT_USER;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_DBT_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV_DBT_ROLE;

GRANT CREATE DBT PROJECT ON SCHEMA DEV_ANALYTICS.DBT TO ROLE DEV_DBT_ROLE;


CREATE WAREHOUSE DEV_DBT_WH WAREHOUSE_SIZE = XSmall;

CREATE DATABASE DEV_ANALYTICS;
CREATE SCHEMA DEV_ANALYTICS.DEV;
CREATE SCHEMA DEV_ANALYTICS.PROD;
CREATE SCHEMA DEV_ANALYTICS.INTEGRATIONS;

USE DEV_ANALYTICS.INTEGRATIONS;
CREATE OR REPLACE SECRET DEV_ANALYTICS.INTEGRATIONS.tb_dbt_git_secret
  TYPE = password
  USERNAME = 'mhaniffajari'
  PASSWORD = 'ghp_xxxx'; --create your token

CREATE OR REPLACE API INTEGRATION tb_dbt_git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/mhaniffajari')
  -- Comment out the following line if your forked repository is public
  ALLOWED_AUTHENTICATION_SECRETS = (DEV_ANALYTICS.INTEGRATIONS.tb_dbt_git_secret)
  ENABLED = TRUE;


CREATE DATABASE PORTFOLIO_TRACKING COMMENT = 'DB for the portfolio tracking project';

CREATE SCHEMA PORTFOLIO_TRACKING.SOURCE_DATA;

CREATE OR REPLACE TABLE PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_POSITION (
    accountID         TEXT,
    symbol            TEXT,
    description       TEXT,
    exchange          TEXT,
    report_date       DATE,
    quantity          NUMBER(38,0),
    cost_base         NUMBER(38,5),
    position_value    NUMBER(38,5),
    currency          TEXT
);

CREATE OR REPLACE FILE FORMAT PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_CSV_FILE_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    ESCAPE = 'NONE'
    ESCAPE_UNENCLOSED_FIELD = '\134'
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    NULL_IF = ('\\N');

--export https://raw.githubusercontent.com/PacktPublishing/Data-engineering-with-dbt/refs/heads/main/Chapter_05/data/ABC_Bank_PORTFOLIO__2021-04-09.csv to PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_POSITION

SELECT * FROM PORTFOLIO_TRACKING.SOURCE_DATA.ABC_BANK_POSITION
